[package]
name    = "hypr-audio"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow     = "1.0.98"
cpal = "0.15.3"
dasp_ring_buffer = "0.11.0"
dasp_sample = "0.11.0"
pipewire = "0.8.0"
rustfft = "6.3.0"
serde      = "1.0.219"
serde_json = "1.0.140"
